### PR TITLE
Added Polygon2, patched get_complete_color_mod

### PR DESCRIPTION
**Pull request by kirilledelman**
Added GPU_Polygon2 function which draws optionally open polygons using line strips. Patched get_complete_color_mod to allow image = NULL.

Please accept my humble contribution.

### CODE REVIEW

**Comment by kirilledelman** [comment]
Something's weird with AppVeyor check - there should be no issues.

**Comment by grimfang4** [comment]
Yeah, the CI is not terribly reliable.  Kind of unfortunate. :-/

**Comment by kirilledelman** [comment]
Yeah, I get the same problem for each automated build - pretty sure it should compile, and yet each build ends with

```
make -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=c:\projects\libs\SDL2 -DSDL_gpu_BUILD_DEMOS=ON -DSDL_gpu_BUILD_TESTS=ON -DSDL_gpu_BUILD_TOOLS=ON -DSDL_gpu_BUILD_SHARED=ON -DSDL_gpu_BUILD_STATIC=ON ..
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SDL2: C:/projects/libs/SDL2/lib/x86/SDL2.lib  
-- Found OpenGL: opengl32   
 Using bundled version of GLEW
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
 Using bundled version of stb-image
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
 Using bundled version of stb-image-write
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: C:/projects/SDL_gpu/build
Specified build project file or folder does not exist: "build\INSTALL.vcxproj"
```

**Comment by grimfang4** [comment]
It looks good.  I think I'd like to rename GPU_Polygon2 to GPU_Polyline and invert the last parameter to something like `closeLoop`.

**Comment by kirilledelman** [comment]
Great, thank you.
Is there something I should've done differently to pass the automated compilation step of pull request?
I can do the renaming and submit another PR.

**Comment by grimfang4** [comment]
I don’t think so.  Usually if I restart the build, it either completes successfully or it fails at a different arbitrary step.

**Pull request merged**
